### PR TITLE
Correct docker-compose.yml name for with_oracle installation

### PR DESCRIPTION
**Pull request by Kiread-work**
Correct the name of "docker-compose.dev.yml" to the proper one "docker-compose.oracle.yml" in paragraph 13

### CODE REVIEW

**Review by TimAle — APPROVED** [review]
It's OK with the change, but commit name is a bit confusing.
What is this number? Also, let's use an imperative mood)

**Comment by Kiread-work** [comment]
Ok. Fix it now, little servant. (Is everything ok with the imperative mood now?)
The number is the support ticket number. IDK why I write it down
;o)

**Comment by TimAle** [comment]
It's still not ok, sorry. Update commit message, please.
https://chris.beams.io/posts/git-commit/#imperative useful reading.

**Comment by Kiread-work** [comment]
Let's try this

**Comment by TimAle** [comment]
It's crazy but PR name and commit message are different things(

**Pull request closed without merging**
