### PR TITLE
HOMS-214 Add Ruby and JS codestyle references

### PR DESCRIPTION
**Pull request by TimAle**

### CODE REVIEW

**Comment by TimAle** [comment]
@GideonEXE @mxsmirnoff your opinion is very important for us!

**Comment by TimAle** [comment]
OK guys :(

**Comment by mxsmirnoff** [comment]
Sorry, I wanted to finish reading both style guides you mentioned before reviewing

**Comment by TimAle** [comment]
@mxsmirnoff 👍 If you have remarks feel free to create PR :)

**Pull request merged**
